version: '3'
services:
  web-app:
    build:
      context: ./web-app
      dockerfile: dockerfile
    ports:
      - "3000:3000"
  mosters:
    build:
      context: ./mosters
      dockerfile: dockerfile
    ports:
      - "8080:8080"